# Generated by Django 3.1.2 on 2021-04-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Joblist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='company',
            field=models.ManyToManyField(null=True, to='Joblist.Company'),
        ),
    ]
