# Generated by Django 3.1.2 on 2021-04-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Joblist', '0002_auto_20210403_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='company',
            field=models.ManyToManyField(blank=True, to='Joblist.Company'),
        ),
    ]
