# Generated by Django 3.1.2 on 2021-04-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Joblist', '0004_auto_20210407_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='qualification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='startdate',
            field=models.DateField(null=True),
        ),
    ]
