# Generated by Django 3.1.2 on 2021-05-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Joblist', '0005_auto_20210407_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='company',
        ),
        migrations.AddField(
            model_name='candidates',
            name='company',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
