# Generated by Django 3.1.2 on 2021-05-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Joblist', '0006_auto_20210501_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
